FROM golang:1.27.1-bookworm AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /app/cmd/konvert-app/exe /app/cmd/server

FROM alpine:3.24.1 AS runner
WORKDIR /app
COPY --from=builder /app/cmd/konvert-app/exe /app
CMD ["/app/exe"]